title: ljmartin.github.io
plugins:
  - jekyll-remote-theme
#description: placeholder for what will be a website
#show_downloads: false
#google_analytics: UA-155552119-1
remote_theme: poole/poole
#remote_theme: benbalter/retlab
